### ISSUE TITLE
Consider locking GleamyShell to v1

### ISSUE THREAD

**Issue by ghost** [darky/glerd#3]
Glerd and other libraries you made that rely on GleamyShell currently don't lock it sufficiently.

I'm about to release v2 this weekend, which comes with some API changes to make it more idiomatic in regards to Gleam's guidelines (favoring `Result` over `Option` for failible functions).

I've created a migration guide, which is part of the readme, and also updated the API documentation, so it shouldn't be that hard.

Just FYI so you've got enough time to lock it accordingly as long as you're adjusting affected areas of your code.

**Comment by darky** [comment]
HI, thanks you!
Feel free to upgrade GleamyShell on any moment, I am ready to support 👍

**Comment by ghost** [comment]
I have a dedicated [issue](https://github.com/patrik-kuehl/gleamyshell/issues/72) for this, which I close as soon as v2 is available on Hex.

**Comment by darky** [comment]
Tests passed, `2.0.0` compatible 👍

**Comment by ghost** [comment]
Yes, tests passed because you simply let assert against `Ok(_)`.

This

```gleam
let assert Ok(_) =
    gleamyshell.execute("gleam", ".", ["format", gen_file_path])
```

should become

```gleam
let assert Ok(CommandOutput(0, _)) =
    gleamyshell.execute("gleam", ".", ["format", gen_file_path])
```

if this is something you want to check. v2 doesn't treat non-zero exit codes as errors any longer. As long as the command could exit, it was a successful execution for GleamyShell. The consumer has to decide what the specific exit code and output mean to them.

**Comment by darky** [comment]
Yeah, I am not worried about `gleam format` successful code ☺️ 
`gleam format` is just "nice to have" feature, non primary
